language: generic
sudo: required
services:
	- docker

before_install:
	- docker build -t amoldesai8/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true USERNAME/react-test npm test
    
after_success:
    - docker build -t amoldesai8/multi-client ./client
    - docker build -t amoldesai8/multi-nginx ./nginx
    - docker build -t amoldesai8/multi-worker ./worker
    - docker build -t amoldesai8/multi-server ./server
    
# Login to docker CLI  
    - echo "$Docker_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
# take those images and push to docker hub

    - docker push amoldesai8/multi-client
    - docker push amoldesai8/multi-nginx
    - docker push amoldesai8/multi-worker
    - docker push amoldesai8/multi-server


